FROM node:22-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json* pnpm-lock.yaml* yarn.lock* ./
RUN \
 if [ -f package-lock.json ]; then npm ci; \
 elif [ -f pnpm-lock.yaml ]; then npm install -g pnpm && pnpm install; \
 elif [ -f yarn.lock ]; then yarn install; \
 else npm install; \
 fi

COPY . .

RUN npm run build

FROM node:22-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3001

COPY --from=builder /app ./

EXPOSE 3001

CMD ["npm", "start", "--", "-p", "3001"]