openapi: 3.0.0
info:
  title: Todo AI Chatbot API
  version: 1.0.0
  description: API for interacting with the Todo AI Chatbot

servers:
  - url: https://api.todoai.com/v1
    description: Production server
  - url: http://localhost:8000/v1
    description: Development server

paths:
  /chat:
    post:
      summary: Send a message to the AI chatbot
      description: Sends a user message to the AI chatbot and receives a response
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: Successful response from the AI chatbot
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /tasks:
    get:
      summary: Get user's tasks
      description: Retrieve all tasks for the authenticated user
      responses:
        '200':
          description: List of user's tasks
          content:
            application/json:
              schema:
                type: object
                properties:
                  tasks:
                    type: array
                    items:
                      $ref: '#/components/schemas/Task'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      summary: Create a new task
      description: Creates a new task for the authenticated user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTaskRequest'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /tasks/{taskId}:
    get:
      summary: Get a specific task
      description: Retrieve a specific task by ID
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
    put:
      summary: Update a task
      description: Updates properties of an existing task
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTaskRequest'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
    delete:
      summary: Delete a task
      description: Permanently deletes a task
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Task deleted successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /auth/login:
    post:
      summary: User login
      description: Authenticates a user and returns an access token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /auth/register:
    post:
      summary: User registration
      description: Creates a new user account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    ChatRequest:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: The user's message to the chatbot
          example: "Add a task to buy groceries"
        conversation_id:
          type: string
          format: uuid
          description: Optional ID of an existing conversation
          example: "123e4567-e89b-12d3-a456-426614174000"

    ChatResponse:
      type: object
      required:
        - response
        - conversation_id
      properties:
        response:
          type: string
          description: The AI chatbot's response
          example: "I've added the task 'buy groceries' to your list."
        conversation_id:
          type: string
          format: uuid
          description: The ID of the conversation
          example: "123e4567-e89b-12d3-a456-426614174000"
        action_performed:
          type: string
          description: The action performed by the AI (e.g., add_task, list_tasks)
          example: "add_task"

    Task:
      type: object
      required:
        - id
        - title
        - status
        - user_id
        - created_at
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the task
          example: "123e4567-e89b-12d3-a456-426614174000"
        title:
          type: string
          description: The task title
          example: "Buy groceries"
        description:
          type: string
          description: Optional detailed description of the task
          example: "Get milk, bread, and eggs"
        status:
          type: string
          enum: [pending, completed]
          description: Current status of the task
          example: "pending"
        user_id:
          type: string
          format: uuid
          description: ID of the user who owns the task
          example: "123e4567-e89b-12d3-a456-426614174001"
        created_at:
          type: string
          format: date-time
          description: Timestamp when the task was created
          example: "2023-01-01T12:00:00Z"
        updated_at:
          type: string
          format: date-time
          description: Timestamp when the task was last updated
          example: "2023-01-01T12:00:00Z"

    CreateTaskRequest:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          description: The task title
          example: "Buy groceries"
        description:
          type: string
          description: Optional detailed description of the task
          example: "Get milk, bread, and eggs"

    UpdateTaskRequest:
      type: object
      properties:
        title:
          type: string
          description: The updated task title
          example: "Buy groceries and cook dinner"
        description:
          type: string
          description: Updated detailed description of the task
          example: "Get milk, bread, eggs, and ingredients for pasta"
        status:
          type: string
          enum: [pending, completed]
          description: Updated status of the task
          example: "completed"

    User:
      type: object
      required:
        - id
        - username
        - email
        - created_at
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the user
          example: "123e4567-e89b-12d3-a456-426614174001"
        username:
          type: string
          description: The user's chosen username
          example: "johndoe"
        email:
          type: string
          format: email
          description: The user's email address
          example: "john.doe@example.com"
        created_at:
          type: string
          format: date-time
          description: Timestamp when the user was created
          example: "2023-01-01T12:00:00Z"
        updated_at:
          type: string
          format: date-time
          description: Timestamp when the user was last updated
          example: "2023-01-01T12:00:00Z"

    LoginRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          description: The user's username
          example: "johndoe"
        password:
          type: string
          description: The user's password
          example: "securePassword123"

    LoginResponse:
      type: object
      required:
        - access_token
        - token_type
      properties:
        access_token:
          type: string
          description: The JWT access token
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        token_type:
          type: string
          description: The type of token (usually "bearer")
          example: "bearer"

    RegisterRequest:
      type: object
      required:
        - username
        - email
        - password
      properties:
        username:
          type: string
          description: The desired username
          example: "johndoe"
        email:
          type: string
          format: email
          description: The user's email address
          example: "john.doe@example.com"
        password:
          type: string
          description: The desired password
          example: "securePassword123"

  responses:
    BadRequest:
      description: Bad request - invalid input
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string
                example: "Invalid input data"
    Unauthorized:
      description: Authentication required or failed
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string
                example: "Authentication credentials were invalid"
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string
                example: "Resource not found"
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string
                example: "Internal server error occurred"